config/routes.rb
RCCIITAlumni::Application.routes.draw do
  get "search/search"
  post "search/search_results"

  get "forum/main"
  get "forum/topic"
  get "forum/post"
  get "forum/new_post"
  post "forum/create_post"
  get "forum/new_reply"
  post "forum/create_reply"
  get "forum/delete_post"

  get "gallery/gallery"
  get "gallery/one_image"

  get "event/event_all"
  get "event/event_one"

  get "admin/user_all"
  get "admin/user_one"
  get "admin/user_toggle"
  get "admin/user_delete"
  get "admin/gallery_upload"
  post "admin/upload_image"
  get "admin/delete_image"
  get "admin/event_create"
  post "admin/create_event"
  get "admin/delete_event"
  get "admin/check_feedback"
  get "admin/one_feedback"
  get "admin/delete_feedback"

  get "user/logger"
  post "user/login"
  get "user/logout"
  get "user/register"
  post "user/create"
  get "user/page"
  get "user/check_pm"
  get "user/check_one_pm"
  get "user/pm"
  post "user/send_pm"
  get "user/delete_pm"
  get "user/edit"
  post "user/commit_edit"
  get "user/delete"

  root "site#home"
  get "site/contact"
  get "site/pdesk"
  get "site/cdesk"
  get "site/feedback"
  post "site/send_feedback"
  get "site/ack"
  get "site/alumniassoc"

end

app/views/admin/check_feedback.html.erb
<div class = 'check-feedback-wrapper'>
	<ul>
		<% @feedbacks.each do |f| %>
			<li>
				<h2><%= link_to f.subject, admin_one_feedback_path(id: f.id) %></h2>
				<h4><%= f.name %></h4>
				<h6><%= f.email %></h6>
			</li>
		<% end %>
	</ul>
</div>

app/views/admin/create_event.html.erb
<%= params %>

app/views/admin/event_create.html.erb
<div class = 'error-message'>
	<% if flash[:error] %>
			<%= flash[:error] %>
	<% end %>
	<span id = 'registration_error' style = 'display:none'></span>
</div>
<%= form_tag admin_create_event_path do %>
	<%= label_tag :date_on, "Event Date:" %>
	<%= date_select :don, :d %>
	<br/>
	<%= label_tag :title, "Event Title:" %>
	<%= text_field_tag :title %>
	<br/>
	<%= label_tag :desc, "Event Description:" %><br/>
	<%= textile_editor_tag :desc, nil, size: "123x17" %>
	<br/>
	<%= textile_editor_initialize %> 
	<%= submit_tag "Create", id: :create %>
<% end %>

app/views/admin/gallery_upload.html.erb
<div class = 'error-message'>
	<% if flash[:error] %>
			<%= flash[:error] %>
	<% end %>
	<span id = 'registration_error' style = 'display:none'></span>
</div>
<%= form_tag admin_upload_image_path, multipart: true do %>
	<%= label_tag :gallery_image, "Image:" %>
	<%= text_field_tag :gallery_image %>
	<br/>
	<%= label_tag :caption, "Caption:" %>
	<%= text_field_tag :caption %>
	<br/>
	<%= label_tag :desc, "Descirption:" %><br/>
	<%= textile_editor_tag :desc, nil, size: "125x23" %>
	<br/>
	<%= textile_editor_initialize %>
	<%= submit_tag "Upload", id: :upload %>
<% end %>

app/views/admin/one_feedback.html.erb
<div class = 'one-feedback-wrapper'>
	<h2><%= @feedback.subject %></h2>
	<h4><%= @feedback.name %></h4>
	<h6><%= @feedback.email %></h6>
	<p><%= txtl @feedback.body %></p>
	<%= link_to "Delete", admin_delete_feedback_path(id: @feedback.id), class: 'button' %>
</div>

app/views/admin/user_all.html.erb
<div class = 'admin-user-all-wrapper'>
	<%= paginate @u_all %>
	<ul>
	<% @u_all.each do |u| %>
		<%= link_to user_page_path id: u.id do %><li>
			<% if u.active %>
				<%= image_tag u.image.to_s, size: "100x100" %>
			<% else %>
				<%= image_tag u.image.to_s, size: "100x100", style: "border-color: black" %>
			<% end %>
			<h3><%= "#{u.fname} #{u.lname}" %></h3>
		</li><% end %>
	<% end %>
	</ul>
</div>

app/views/admin/user_delete.html.erb
<h1>Admin#user_delete</h1>
<p>Find me in app/views/admin/user_delete.html.erb</p>

app/views/admin/user_one.html.erb
<h1>Admin#user_one</h1>
<p>Find me in app/views/admin/user_one.html.erb</p>