config/routes.rb
RCCIITAlumni::Application.routes.draw do
  get "search/search"
  post "search/search_results"

  get "forum/main"
  get "forum/topic"
  get "forum/post"
  get "forum/new_post"
  post "forum/create_post"
  get "forum/new_reply"
  post "forum/create_reply"
  get "forum/delete_post"

  get "gallery/gallery"
  get "gallery/one_image"

  get "event/event_all"
  get "event/event_one"

  get "admin/user_all"
  get "admin/user_one"
  get "admin/user_toggle"
  get "admin/user_delete"
  get "admin/gallery_upload"
  post "admin/upload_image"
  get "admin/delete_image"
  get "admin/event_create"
  post "admin/create_event"
  get "admin/delete_event"
  get "admin/check_feedback"
  get "admin/one_feedback"
  get "admin/delete_feedback"

  get "user/logger"
  post "user/login"
  get "user/logout"
  get "user/register"
  post "user/create"
  get "user/page"
  get "user/check_pm"
  get "user/check_one_pm"
  get "user/pm"
  post "user/send_pm"
  get "user/delete_pm"
  get "user/edit"
  post "user/commit_edit"
  get "user/delete"

  root "site#home"
  get "site/contact"
  get "site/pdesk"
  get "site/cdesk"
  get "site/feedback"
  post "site/send_feedback"
  get "site/ack"
  get "site/alumniassoc"

end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  def main
  	unless current_user
  		flash[:error] = "Only registered users may access the Open Forum."
  		return redirect_to root_path
  	end

    set_title "Open Forum"

  	@topics = Topic.all.order('updated_at DESC').page(params[:page]).per(10)
  end

  def topic
  	unless current_user
  		flash[:error] = "Only registered users may access the Open Forum."
  		return redirect_to root_path
  	end

  	@topic = Topic.find params[:id]
  	@posts = Post.where( topic_id: params[:id] ).order( 'updated_at ASC').page(params[:page]).per(10)

    set_title @topic.title
  end

  def post
  	unless current_user
  		flash[:error] = "Only registered users may access the Open Forum."
  		return redirect_to root_path
  	end

    set_title 'New Post'
  end

  def new_post
  	unless current_user
  		flash[:error] = "Only registered users may access the Open Forum."
  		return redirect_to root_path
  	end
  end

  def new_reply
    unless current_user
      flash[:error] = "Only registered users may access the Open Forum."
      return redirect_to root_path
    end

    set_title 'Reply to Post'
  end

  def create_reply
  	unless current_user
  		flash[:error] = "Only registered users may access the Open Forum."
  		return redirect_to root_path
  	end

    if params[:title] === "" or params[:content] === ""
      flash[:error] = "All fields must be filled in."
      return redirect_to forum_new_reply_path
    end

  	Post.create title: params[:title], user_id: current_user.id, topic_id: params[:topic_id], content: params[:content]
  	redirect_to forum_topic_path(id: params[:topic_id])
  end

  def create_post
  	unless current_user
  		flash[:error] = "Only registered users may access the Open Forum."
  		return redirect_to root_path
  	end

    if params[:title] === "" or params[:content] === ""
      flash[:error] = "All fields must be filled in."
      return redirect_to forum_new_post_path
    end

  	topic = Topic.create title: params[:title], user_id: current_user.id
  	post = Post.create title: params[:title], content: params[:content], user_id: current_user.id, 
  		topic_id: topic.id, primary: true

  	redirect_to forum_topic_path( id: topic.id)
  end

  def delete_post
  	unless current_user
  		flash[:error] = "Only registered users may access the Open Forum."
  		return redirect_to root_path
  	end

  	post = Post.find(params[:id])
  	tid = post.topic.id

    unless post.user.id === current_user.id or is_admin?
      return redirect_to forum_topic_path(id: tid)
    end

  	if post.primary
  		Topic.find(tid).destroy

  		Post.where(topic_id: tid).each do |p|
  			p.delete
  		end
  		return redirect_to forum_main_path
  	else
  		post.delete
   	end
  	return redirect_to forum_topic_path(id: tid)
  end
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/views/forum/main.html.erb
<div class = 'open-forum-wrapper'>
<h2>Open Forum</h2>
<%= link_to "New Post", forum_new_post_path, class: 'button' %>
<div class = 'topics-list-container'>
	<ul>
		<%= paginate @topics %>
		<% @topics.each do |t| %>
			<%= link_to forum_topic_path id: t.id do %>
				<li>
					<h4><%= t.title %></h4><% end %>
					<span class = 'owner'>
						<%= image_tag t.user.image.to_s, size: "40x40" %>
						<div class = 'info-text'>
							<%= link_to "started by #{t.user.fname} #{t.user.lname}", user_page_path(id: t.user.id) %><br/>
							<%= "created on "+t.created_at.strftime("%d/%m/%Y  %I:%M %p") %><br/>
							<%= "total posts "+Post.where(topic_id: t.id).count.to_s %>
						</div>
					</span>
				</li>
		<% end %>
	</ul>
</div>
</div>

app/views/forum/new_post.html.erb
<div class = 'error-message'>
	<% if flash[:error] %>
			<%= flash[:error] %>
	<% end %>
	<span id = 'registration_error' style = 'display:none'></span>
</div>
<%= form_tag forum_create_post_path do %>
	<%= text_field_tag :title %>
	<br/>
	<%= textile_editor_tag :content, nil, size: "125x17" %>
	<br/>
	<%= textile_editor_initialize %>
	<%= submit_tag "Create Post", id: 'create_post', class: 'button' %>
<% end %>

app/views/forum/new_reply.html.erb
<div class = 'error-message'>
	<% if flash[:error] %>
			<%= flash[:error] %>
	<% end %>
	<span id = 'registration_error' style = 'display:none'></span>
</div>
<%= form_tag forum_create_reply_path do %>
	<%= text_field_tag :title %>
	<br/>
	<%= textile_editor_tag :content, nil, size: "125x17" %>
	<br/>
	<%= textile_editor_initialize %>
	<%= hidden_field_tag :topic_id, params[:id] %>
	<%= submit_tag "Post Reply", id: 'post_reply', class: 'button' %>
<% end %>

app/views/forum/post.html.erb
<h1>Forum#post</h1>
<p>Find me in app/views/forum/post.html.erb</p>

app/views/forum/topic.html.erb
<div class = 'topic-wrapper'>
<h2><%= @topic.title %></h3>
<%= link_to "Reply", forum_new_reply_path(id: @topic.id), class: 'button' %>
<ul>
	<%= paginate @posts %>
	<% @posts.each do |p| %>
		<li>
			<div class = 'user-info'><%= link_to user_page_path(id: p.user.id) do %>
				<h4><%= p.user.fname %></h4>
				<%= image_tag p.user.image.to_s, size: "100x100" %>
				<p><%= p.user.typeof %></p>
			<% end %></div>
			<div class = 'post-info'>
				<h4><%= p.title %></h4>
				<h6><%= p.created_at.strftime "%d/%m/%Y  %I:%M %p" %></h6>
				<hr/>
				<p><%= txtl p.content %></p>
				<% if p.user.id === current_user.id or is_admin? %> 
					<%= link_to "Delete", forum_delete_post_path(id: p.id), class: 'button' %>
				<% end %>
			</div>
		</li>
	<% end %>
</ul>
</div>