config/routes.rb
RCCIITAlumni::Application.routes.draw do
  get "search/search"
  post "search/search_results"

  get "forum/main"
  get "forum/topic"
  get "forum/post"
  get "forum/new_post"
  post "forum/create_post"
  get "forum/new_reply"
  post "forum/create_reply"
  get "forum/delete_post"

  get "gallery/gallery"
  get "gallery/one_image"

  get "event/event_all"
  get "event/event_one"

  get "admin/user_all"
  get "admin/user_one"
  get "admin/user_toggle"
  get "admin/user_delete"
  get "admin/gallery_upload"
  post "admin/upload_image"
  get "admin/delete_image"
  get "admin/event_create"
  post "admin/create_event"
  get "admin/delete_event"
  get "admin/check_feedback"
  get "admin/one_feedback"
  get "admin/delete_feedback"

  get "user/logger"
  post "user/login"
  get "user/logout"
  get "user/register"
  post "user/create"
  get "user/page"
  get "user/check_pm"
  get "user/check_one_pm"
  get "user/pm"
  post "user/send_pm"
  get "user/delete_pm"
  get "user/edit"
  post "user/commit_edit"
  get "user/delete"

  root "site#home"
  get "site/contact"
  get "site/pdesk"
  get "site/cdesk"
  get "site/feedback"
  post "site/send_feedback"
  get "site/ack"
  get "site/alumniassoc"

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password

	has_many :topics
	has_many :posts

	before_create { generate_token :auth_token }
	before_save :encrypt_password

	def authenticate pass
		new_hash = BCrypt::Engine.hash_secret pass, self.password_salt
		if  new_hash === self.password_hash
			return true
		end
		false
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret password, password_salt
		end
	end

	def generate_token column
		begin
			self[column] = 	SecureRandom.urlsafe_base64
		end while User.exists? column => self[column]
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def logger
    set_title 'Login'
  end

  def login
    user = User.find_by_email params[:email]

    if !user
      flash[:error] = "Email does not exist."
      return redirect_to user_logger_path
    elsif !user.authenticate params[:password]
      flash[:error] = "Password incorrect."
      return redirect_to user_logger_path
    elsif !user.active
      flash[:error] = "User account not yet active. Wait twenty-four hours or contact admin."
      return redirect_to user_logger_path
    end

    cookies[:auth_token] = user.auth_token

    flash[:message] = "User #{user.fname} #{user.lname} successfully logged in."
    redirect_to root_path
  end

  def logout
    cookies.delete :auth_token
    redirect_to root_path
  end

  def register
    set_title 'Register'
    @departments = Department.all
  end

  def create
    if params[:email] === "" || params[:password] === ""
      flash[:error] = "Email or password missing."
      return redirect_to user_register_path
    elsif User.find_by_email params[:email]
      flash[:error] = "Email already exists."
      return redirect_to user_register_path
    end

    dtime = DateTime.new params[:dob]['d(1i)'].to_i, params[:dob]['d(2i)'].to_i, params[:dob]['d(3i)'].to_i
    @newUser = User.new typeof: params[:typeof], fname: params[:fname], lname: params[:lname], dob: dtime, 
      email: params[:email], phone: params[:phone], department: Department.find(params[:department]).name,
      department_id: params[:department], password: params[:password]

    @newUser.image = params[:image]

    if params[:typeof] === 'Alumni'
      @newUser.status = params[:status] if params[:status]
      @newUser.inst = params[:inst] if params[:inst]
      @newUser.yearofpassing = params[:date][:year]
      @newUser.posit = params[:posit] if params[:posit]
    elsif params[:typeof] === 'Teacher'
      @newUser.posit = params[:posit]
    elsif params[:typeof] === 'Student'
      @newUser.yearofpassing = params[:date][:year]
    end

    if params[:email] === 'admin@rcciitalumni.in' or params[:email] === 'avishekga@gmail.com'
      @newUser.active = true
    else
      @newUser.active = false
    end

    unless @newUser.valid?
      flash[:error] = "Something has gone wrong. Check the format of your image."
      return redirect_to user_register_path
    end
    
    @newUser.save
  end

  def page
    unless current_user
      return redirect_to root_path
    end

    @cu = User.find params[:id]

    set_title "#{@cu.fname} #{@cu.lname}"
  end

  def check_pm
    unless current_user
      return redirect_to root_path
    end

    set_title 'P.M.'

    @pms = Pm.where(to: current_user.id).order(seen: :desc, created_at: :desc).page(params[:page]).per(10)
  end

  def check_one_pm
    unless current_user and Pm.find(params[:id]).to === current_user.id
      return redirect_to root_path
    end

    @pm = Pm.find params[:id]

    @pm.update_attribute :seen, true
    set_title "#{@pm.subject}"
  end

  def pm
    unless current_user
      return redirect_to root_path
    end

    set_title 'Send P.M.'

    @cu = User.find params[:id]
    @subject = ""
    @subject = params[:subject] if params[:subject]
  end

  def send_pm
    unless current_user
      return redirect_to root_path
    end

    user = User.find params[:receiver]

    if user and Pm.where(to: user.id).count < 19
      Pm.create subject: params[:subject], body: params[:body], to: user.id, from: current_user.id
      flash[:message] = "PM Sent."
      return redirect_to user_page_path(id: params[:receiver])
    end
      
    flash[:message] = "User's inbox is full."
    return redirect_to user_page_path(id: params[:receiver])
  end

  def delete_pm
    unless current_user
      return redirect_to root_path
    end

    @pm = Pm.find params[:id]

    unless @pm.to === current_user.id
      return redirect_to user_check_pm_path
    end

    @pm.delete

    return redirect_to user_check_pm_path
  end

  def edit
    set_title 'Edit Account Details'
  end

  def commit_edit
    unless params[:image] === ""
      current_user.update_attribute :image, params[:image]
    end

    unless current_user.email === params[:email]
      if User.find_by_email params[:email]
        flash[:error] = "Email already exists."
        return redirect_to user_edit_path
      end
    end

    current_user.update_attributes email: params[:email], phone: params[:phone]

    if current_user.typeof === "Alumni"
      current_user.update_attributes status: params[:status], inst: params[:inst]
    end

    return redirect_to user_page_path(id: current_user.id)
  end

  def delete
    unless current_user
      return redirect_to root_path
    end

    cur = current_user
    cur.destroy
    cookies.delete :auth_token
    redirect_to root_path
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/check_one_pm.html.erb
<div class = "one-pm-wrapper">
	<h2><%= @pm.subject %></h2>
	<h4><%= link_to "#{User.find(@pm.from).fname} #{User.find(@pm.from).lname}", user_page_path(id: @pm.from) %></h4>
	<h6><%= @pm.created_at.strftime "%d/%m/%Y" %></h6>	
	<div class = 'pm-body'><%= txtl @pm.body %></div>
	<br/>
	<%= link_to 'Delete', user_delete_pm_path(id: @pm.id), class: 'button' %>
	<%= link_to 'Reply', user_pm_path(id: @pm.from, subject: "Reply: #{@pm.subject}"), class: 'button' %>
</div>

app/views/user/check_pm.html.erb
<div class = 'check-pm-wrapper'>
	<h2><%= "#{current_user.fname}'s Messages" %></h2>

	<div class = 'pm-messages'>
		<ul>
		<%= paginate @pms %>
		<%= "No Messages." if @pms.empty? %>
		<% @pms.each do |pm| %>
			<li><%= image_tag User.find(pm.from).image.to_s, size: "40x40" %>
				<span class= "pm-subject"><%= link_to pm.subject, user_check_one_pm_path(id: pm.id) %></span>
				<span class = 'new-pm-indicator'><%= 'New' unless pm.seen %></span><br/>
				<%= link_to "#{User.find(pm.from).fname} #{User.find(pm.from).lname}", user_page_path(id: pm.from) %>&nbsp;&nbsp;
				<em><%= pm.created_at.strftime "%d/%m/%Y  %I:%M %p" %></em>
			</li>
		<% end %>	
	</div>
</div>

app/views/user/create.html.erb
<div class = 'create-account-message'>
	<% if @newUser.typeof.eql? "Alumni" or @newUser.typeof.eql? "Teacher" %>
		<h2>Congratulations <%= "#{@newUser.fname} #{@newUser.lname}" %> on being registered with RCCIIT Alumni !!</h2>
		<p>You have been registered with the email: <%= @newUser.email %>.</p>
		<p>For completing the registration process please pay the required amount in the given account details:</p>
		<p>Registration Fee : 100 INR (One time)</p>
		<p>Membership Fee : 100 INR (Yearly)</p>
		<p></p>
		<p>A/c No: 402210110002300 (Savings account)</p>
		<p>IFSC Code:- BKID0004022</p>
		<p>BANK OF INDIA, BELIAGHATA</p>

		<p>After payment is done please contact the admin for details of activation.</p>
	<% else %>
		<h2>Congratulations <%= "#{@newUser.fname} #{@newUser.lname}" %> on being registered with RCCIIT Alumni !!</h2>
		<p>You have been registered with the email: <%= @newUser.email %>.</p>
		<p>Please wait 24 hours for activation by the admin.</p>
	<% end %>
</div>

app/views/user/delete.html.erb
<h1>User#delete</h1>
<p>Find me in app/views/user/delete.html.erb</p>

app/views/user/edit.html.erb
<div class = "edit-user-wrapper">
	<div class = "error-message">
		<%= flash[:error] if flash[:error] %>
	</div>
	<%= form_tag user_commit_edit_path, multipart: true do %>
		<%= label_tag :image, "Image:" %><br/>
		<%= text_field_tag :image %>
		<br/><br/>
		<% if current_user.typeof === 'Alumni' %>
			<%= label_tag :status, "Current Status:" %><br/>
			<%= text_field_tag :status, current_user.status %>
			<br/><br/>
			<%= label_tag :inst, "Institution or Organization:" %><br/>
			<%= text_field_tag :inst, current_user.inst %>
			<br/><br/>
		<% end %>
		<%= label_tag :email, "Email:" %><br/>
		<%= email_field_tag :email, current_user.email %>
		<br/><br/>
		<%= label_tag :phone, "Phone No.:" %><br/>
		<%= text_field_tag :phone, current_user.phone %> <span class = 'form-field-info'>Ten digit phone number, no spaces or hyphen.</span>
		<br/><br/>
		<%= label_tag :password, "Password:" %><br/>
		<%= password_field_tag :password %> <span class = 'form-field-info'>Minimum 6 characters, maximum 16, letters and numbers only.</span>
		<br/><br/>
		<%= label_tag :conf_password, "Confirm Password:" %><br/>
		<%= password_field_tag :confirm_password %>
		<br/><br/>
		<%= submit_tag "Update", id: 'update', class: 'button' %>
	<% end %>
</div>

app/views/user/logger.html.erb
<%= javascript_include_tag :logger %>

<div class = 'error-message' id = 'logger_error' style = 'display:none'></div>
<div class = 'error-message'>
	<% if flash[:error] %>
			<%= flash[:error] %>
	<% end %>
</div>

<%= form_tag user_login_path do %>
	<%= label_tag :email, "Email:" %><br/>
	<%= email_field_tag :email %>
	<br/><br/>
	<%= label_tag :password, "Password:" %><br/>
	<%= password_field_tag :password %>
	<br/><br/>
	<%= submit_tag "Login", id: 'login_button', class: 'button' %>
<% end %>

app/views/user/login.html.erb
<h1>User#login</h1>
<p>Find me in app/views/user/login.html.erb</p>

app/views/user/logout.html.erb
<h1>User#logout</h1>
<p>Find me in app/views/user/logout.html.erb</p>

app/views/user/page.html.erb
<div class = 'user-page-wrapper'>

	<div class = 'confirm-message'>
		<%= flash[:message] if flash[:message] %>
	</div>
<div class = 'user-image-box'>
	<%= image_tag @cu.image.to_s, size: "300x300" %>
	<p><%= @cu.typeof %></p>
</div>
<div class = 'user-details'>
	<div class = 'user-page-head'>
		<h2><%= @cu.fname %> <%= @cu.lname %></h2>
		<em><u><%= link_to @cu.email, "mailto:#{@cu.email}", class: 'user-email' %></u></em>
	</div>

	<p><span class = 'prop'>Contact No.</span> <br/><%= @cu.phone if @cu.phone %></p>
	<p><span class = 'prop'>D.O.B</span> <br/><%= @cu.dob.strftime( "%d/%m/%Y") if @cu.dob %></p>
	<p><span class = 'prop'>Class Of</span> <br/><%= @cu.yearofpassing if @cu.yearofpassing %></p>
</div>

<div class = 'department-specific'>
	<p><span class = 'prop'>Department</span> <br/><%= @cu.department if @cu.department %></p>
	<% if @cu.typeof === "Alumni" %>
		<% if @cu.status != "" %><p><span class = 'prop'>Current Status</span> <br/><%= @cu.status %></p><% end %>
		<% if @cu.inst != "" %><p><span class = 'prop'>Institution or Organization</span> <br/><%= @cu.inst %></p><% end %>
		<% if @cu.posit != "" %><p><span class = 'prop'>Post</span> <br/><%= @cu.posit if @cu.posit %></p><% end %>	
	<% end %>
	<% if @cu.typeof === "Teacher" %>
		<p><span class = 'prop'>Post</span> <br/><%= @cu.posit if @cu.posit %></p>
	<% end %>
</div>
<% if current_user.id === @cu.id %>
	<p>
		<%=link_to "Edit", user_edit_path(id: @cu.id), class: 'button' %> 
		<%= link_to "Delete", user_delete_path, class: 'button' %>
	</p>
<% elsif is_admin? %>
	<p>
		<%= link_to "P.M", user_pm_path(id: @cu.id), class: 'button' %> 
		<% if @cu.active %>
			<%= link_to 'Deactivate', admin_user_toggle_path(id: @cu.id), class: 'button' %>
		<% else %>
			<%= link_to 'Activate', admin_user_toggle_path(id: @cu.id), class: 'button' %>
		<% end %>
		<%= link_to 'Delete', admin_user_delete_path(id: @cu.id), class: 'button' %>
	</p>
<% else %>
	<p><%= link_to "P.M", user_pm_path(id: @cu.id), class: 'button' %></p>
<% end %>
</div>

app/views/user/pm.html.erb
<div class = 'pm-wrapper'>
	<%= form_tag user_send_pm_path do %>
		<%= label_tag :to, "To:" %><br/>
		<%= label_tag :to, "#{@cu.fname} #{@cu.lname}" %>
		<br/><br/>
		<%= label_tag :subject, "Subject:" %><br/>
		<%= text_field_tag :subject, @subject %>
		<br/><br/>
		<%= label_tag :body, "Body:" %><br/>
		<%= textile_editor_tag :body, nil, size: "125x17" %>
		<br/><br/>
		<%= hidden_field_tag :receiver, @cu.id %>
		<%= textile_editor_initialize %>
		<%= submit_tag "Send", id: 'send', class: 'button' %>
		<%= link_to "Inbox", user_check_pm_path, class: 'button' %>
	<% end %>
</div>

app/views/user/register.html.erb
<%= javascript_include_tag :registration %>

<div class = 'register-wrapper'>
<div class = 'error-message'>
	<% if flash[:error] %>
			<%= flash[:error] %>
	<% end %>
	<span id = 'registration_error' style = 'display:none'></span>
</div>
<div class = 'register-form-wrapper'>
<%= form_tag user_create_path, multipart: true do %>
	<%= label_tag :typeof, "Type of Account:" %><br/>
	<%= select_tag :typeof, "<option selected='selected'>Alumni</option><option>Teacher</option><option>Student</option>".html_safe %>
	<br/><br/>
	<%= label_tag :image, "Image:" %><span class = "mandatory-field">*</span><br/>
	<%= text_field_tag :image %> <span class = 'form-field-info'>Copy and paste any image url</span>
	<br/><br/>
	<%= label_tag :fname, "First Name:" %><span class = "mandatory-field">*</span><br/>
	<%= text_field_tag :fname %>
	<br/><br/>
	<%= label_tag :lname, "Last Name:" %><span class = "mandatory-field">*</span><br/>
	<%= text_field_tag :lname %>
	<br/><br/>
	<%= label_tag :dob, "Date of Birth:" %><span class = "mandatory-field">*</span><br/>
	<%= date_select :dob, :d, start_year: 1940, end_year: Time.now.year-17 %>
	<br/><br/>
	<%= label_tag :department, "Department:" %><span class = "mandatory-field">*</span><br/>
	<%= select_tag :department, options_from_collection_for_select(@departments, :id, :name) %>
	<br/><br/>
	<%= label_tag :yearofpassing, "Year of Passing:" %><span class = "mandatory-field">*</span><br/>
	<%= select_year Date.today, start_year: 1940 %>
	<br/><br/>
	<%= label_tag :status, "Current Status:" %><br/>
	<%= text_field_tag :status %>
	<br/><br/>
	<%= label_tag :inst, "Institution or Organization:" %><br/>
	<%= text_field_tag :inst %>
	<br/><br/>
	<%= label_tag :posit, "Position:" %><span class = "mandatory-field">*</span><br/>
	<%= text_field_tag :posit, nil %>
	<br/><br/>
	<%= label_tag :email, "Email:" %><span class = "mandatory-field">*</span><br/>
	<%= email_field_tag :email %>
	<br/><br/>
	<%= label_tag :phone, "Phone No.:" %><span class = "mandatory-field">*</span><br/>
	<%= text_field_tag :phone %> <span class = 'form-field-info'>13 digit phone number, no spaces or hyphen, include country code as "091" or similar.</span>
	<br/><br/>
	<%= label_tag :password, "Password:" %><span class = "mandatory-field">*</span><br/>
	<%= password_field_tag :password %> <span class = 'form-field-info'>Minimum 6 characters, maximum 16, letters and numbers only.</span>
	<br/><br/>	
	<%= label_tag :conf_password, "Confirm Password:" %><span class = "mandatory-field">*</span><br/>
	<%= password_field_tag :confirm_password %>
	<br/><br/>
	<%= submit_tag "Register", id: 'register', class: 'button' %>
<% end %>
</div>
</div>