config/routes.rb
RCCIITAlumni::Application.routes.draw do
  get "search/search"
  post "search/search_results"

  get "forum/main"
  get "forum/topic"
  get "forum/post"
  get "forum/new_post"
  post "forum/create_post"
  get "forum/new_reply"
  post "forum/create_reply"
  get "forum/delete_post"

  get "gallery/gallery"
  get "gallery/one_image"

  get "event/event_all"
  get "event/event_one"

  get "admin/user_all"
  get "admin/user_one"
  get "admin/user_toggle"
  get "admin/user_delete"
  get "admin/gallery_upload"
  post "admin/upload_image"
  get "admin/delete_image"
  get "admin/event_create"
  post "admin/create_event"
  get "admin/delete_event"
  get "admin/check_feedback"
  get "admin/one_feedback"
  get "admin/delete_feedback"

  get "user/logger"
  post "user/login"
  get "user/logout"
  get "user/register"
  post "user/create"
  get "user/page"
  get "user/check_pm"
  get "user/check_one_pm"
  get "user/pm"
  post "user/send_pm"
  get "user/delete_pm"
  get "user/edit"
  post "user/commit_edit"
  get "user/delete"

  root "site#home"
  get "site/contact"
  get "site/pdesk"
  get "site/cdesk"
  get "site/feedback"
  post "site/send_feedback"
  get "site/ack"
  get "site/alumniassoc"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title_field %> | RCCIITAlumni</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Expletus+Sans:700|Exo+2|Cardo' rel='stylesheet' type='text/css'>

  <meta name="viewport" content="width=1366, maximum-scale=1">
</head>
<body>
<div class = 'universal-wrapper'>
<header>
	<%= link_to root_path do %>
		<%= image_tag 'logo-text.png', alt: "logo text", class: 'header-text' %>
		<h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-------"mission to get closer and stronger..."</h2>
	<% end %>
	<div class = 'logbar'>
		<ul>
			<% if current_user %>
				<li><%= link_to "#{current_user.fname} #{current_user.lname}", user_page_path(id: current_user.id) %></li>
				<li><%= link_to 'Check P.M.', user_check_pm_path %></li>
				<li><%= link_to 'Search', search_search_path %></li>
				<li><%= link_to 'Logout', user_logout_path %></li>
			<% else %>
				<li><%= link_to 'Login', user_logger_path %></li>
				<li><%= link_to 'Register', user_register_path %></li>
			<% end %>
		</ul>
	</div>
	<nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Principal's Desk", site_pdesk_path %></li>
			<li><%= link_to "Chairman's Desk", site_cdesk_path %></li>
			<li><%= link_to "Gallery", gallery_gallery_path %></li>
			<% if current_user %>
				<li><%= link_to "Open Forum", forum_main_path %></li>
			<% end %>
			<li><%= link_to "Events", event_event_all_path %></li>
			<li><%= link_to "Payment Details", site_ack_path %></li>
			<li><%= link_to "Association Details", site_alumniassoc_path %></li>
			<li><%= link_to "Feedback", site_feedback_path %></li>
		</ul>
	</nav>
	<% if is_admin? %>
	<div class = 'admin-bar'>
		<ul>
			<li><%= link_to 'Manage Users', admin_user_all_path %></li>
			<li><%= link_to 'Upload to Gallery', admin_gallery_upload_path %></li>
			<li><%= link_to 'Create Events', admin_event_create_path %></li>
			<li><%= link_to 'Check Feedbacks', admin_check_feedback_path %></li>
		</ul>
	</div>
	<% end %>
</header>

<div class = 'yield-wrapper'>
<div class = "spacer"></div>
<%= yield %>

</div>
	
	<footer>
		
		<h1>Contact Us:</h1>
		<table CELLSPACING=0 CELLPADDING=5>
    <tr>

        <td width="50px"><h4>Avishek Ganguly</h4></td>
        <td><h4>Ayanjit Pal</h4></td>
    </tr>
    <tr>
        <td>+91 9475133819</td>
        <td>+91 9647954892</td>
    </tr>
    <tr>
        <td>avishekga@gmail.com</td>
        <td>ayanjit.rcciit@gmail.com</td>
    </tr>
</table>
	
	</footer>
</div>
</body>
</html>